### ISSUE TITLE
Get error when trying to make ByteTracker

### ISSUE THREAD

**Issue by Lehieubkhn** [chirag4798/Byte-Deepstream#1]
![image](https://user-images.githubusercontent.com/31854390/158290357-f7770c7e-168a-4043-b978-dc521b86fdc5.png)
Thanks for your work, but I got this error when I tried to make ByteTracker. How can I fix it?

**Comment by callmesora** [comment]
I'm having a similar problem, did you solve it? @Lehieubkhn

**Comment by callmesora** [comment]
Update:
I changed:
(1)
pQuery -> supportBatchProcessing = true;
to:
pQuery-> batchMode = NvMOTBatchMode_Batch;

(2)
void NvMOT_RemoveStreams(...){}
to:
NvMOTStatus NvMOT_RemoveStreams(...);

**Comment by chirag4798** [comment]
The code was built for DeepStream5.1, the NvTracker API's for DeepStream6 have been modified a bit. The changes that @callmesora mentioned would work with Deepstream6

**Comment by chirag4798** [comment]
check latest enhancements for the fix
